In [5]:
import numpy as np
o = np.ones((3, 16))
z = np.zeros((3, 16))
keep = [0, 1, 2, 3, 4, 5, 6, 7, 8, 31, 32, 33, 34, 35, 36, 37]
print(np.vstack((o,z)))


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [13]:
jac = np.random.rand(6, 48)
jac[:, keep] = np.vstack((o,z))
print(jac)

[[1.         1.         1.         1.         1.         1.
  1.         1.         1.         0.98288772 0.15053098 0.14228924
  0.15427941 0.92767619 0.67698284 0.95208311 0.27456062 0.01813378
  0.14429371 0.42151248 0.12728511 0.06325794 0.64335278 0.82735439
  0.92064445 0.90482508 0.94831784 0.86574045 0.87185404 0.42713198
  0.31389345 1.         1.         1.         1.         1.
  1.         1.         0.14989415 0.95999292 0.15737784 0.74542096
  0.4906409  0.00800035 0.34083877 0.83710233 0.46272466 0.83916423]
 [1.         1.         1.         1.         1.         1.
  1.         1.         1.         0.08886943 0.75657933 0.15674176
  0.43033968 0.33791297 0.07324007 0.65810036 0.22078049 0.24349209
  0.72356418 0.796669   0.48973887 0.95130952 0.39452256 0.6291174
  0.2765872  0.09694165 0.87866198 0.95433069 0.4619655  0.67997452
  0.32051328 1.         1.         1.         1.         1.
  1.         1.         0.32508176 0.56176758 0.73771232 0.1089958
  0.69759575 

In [23]:
wonwon = [11, 22, 23, 35, 36]

In [24]:
print(jac[:, wonwon])

[[0.14228924 0.64335278 0.82735439 1.         1.        ]
 [0.15674176 0.39452256 0.6291174  1.         1.        ]
 [0.87344672 0.94430573 0.06201002 1.         1.        ]
 [0.12796479 0.95867108 0.24830265 0.         0.        ]
 [0.58019118 0.44222566 0.06038881 0.         0.        ]
 [0.58507838 0.41426164 0.94422591 0.         0.        ]]
